
const allQueries = {
  adaptCodeQuery: require("./adaptCodeQuery.js"),
  adaptDataTableQuery: require("./adaptDataTableQuery.js"),
  adaptLevelQuery: require("./adaptLevelQuery.js"),
  adaptStudentChartQuery: require("./adaptStudentChartQuery"),
  adaptStudentsQuery: require("./adaptStudentsQuery.js"),
  aggregatePageViewsQuery: require("./aggregatePageViewsQuery.js"),
  allAdaptAssignmentsQuery: require("./allAdaptAssignmentsQuery.js"),
  allAdaptCoursesQuery: require("./allAdaptCoursesQuery.js"),
  allCoursesQuery: require("./allCoursesQuery.js"),
  allStudentsQuery: require("./allStudentsQuery.js"),
  assignmentCountQuery: require("./assignmentCountQuery").assignmentCountQuery,
  assignmentCountQuerySpecificCourse: require("./assignmentCountQuery").assignmentCountQuerySpecificCourse,
  averagePageViewsQuery: require("./averagePageViewsQuery.js"),
  chapterChartQuery: require("./chapterChartQuery.js"),
  courseUnitsQuery: require("./courseUnitsQuery.js"),
  dataTableQuery: require("./dataTableQuery.js"),
  getTagQuery: require("./getTagQuery.js"),
  individualDataQuery: require("./individualDataQuery.js"),
  individualGradePageViewsQuery: require("./individualGradePageViewsQuery.js"),
  individualPageViewsQuery: require("./individualPageViewsQuery.js"),
  individualTimelineQuery: require("./individualTimelineQuery.js"),
  pageCountQuery: require("./pageCountQuery.js"),
  studentAdaptAssignmentQuery: require("./studentAdaptAssignmentQuery.js"),
  studentChartQuery: require("./studentChartQuery.js"),
  studentTextbookEngagementQuery: require("./studentTextbookEngagementQuery.js"),
  aggregateAssignmentViewsQuery: require("./aggregateAssignmentViewsQuery.js"),
  allAssignmentGradesQuery: require("./allAssignmentGradesQuery.js"),
  pageLookupQuery: require("./pageLookupQuery.js"),
  individualAssignmentSubmissionsQuery: require("./individualAssignmentSubmissionsQuery.js"),
  gradesFromAdaptQuery: require("./gradesFromAdapt.js"),
  ewsModelDataQuery: require("./ewsModelDataQuery.js"),
  ewsModelAdaptQuery: require("./ewsModelAdaptQuery.js"),
  averageGradesFromGradebookQuery: require("./averageGradesFromGradebookQuery.js"),
  assignmentCountFromGradebookQuery: require("./assignmentCountFromGradebookQuery")
}

module.exports = allQueries
